### ISSUE TITLE
Django 1.10 migration

### ISSUE THREAD

**Issue by GeoTob** [foundertherapy/django-cryptographic-fields#20]
Just checking in to see how django 1.10 compatibility is coming along?

I see there's a branch already, and installing from that branch seems to work OK with django 1.10.x at the moment. Are there any major obstacles to solve before you can push a new version?

**Comment by GhalebKhaled** [comment]
Codingwise it's ready, and should be merged within few days - I'm pending a colleage review before merging to master

**Comment by GeoTob** [comment]
Thanks @GhalebKhaled, I'll be using it then :)
